name: Setup Project

description: Install node and dependancies

inputs:
  node-version:
    required: true

outputs:
  node-version:
    value: ${{ steps.version.outputs.node }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm install
      shell: bash
    - id: version
      run: echo "node=${{inputs.node-version}}" >> "$GITHUB_OUTPUT"
      shell: bash