name: CI CD Learning

on:
  push

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run some steps
        run: |
          echo "My name is Suresh"
          echo "Learning GitHub actions"
          pwd
          node -v
