### Actions

# name: CI CD | GitHub actions
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   demo:
#     runs-on:
#       ubuntu-latest
    
#     steps:
#       - run: |
#           echo "Files before checkout : "
#           ls

#       - uses: actions/checkout@v4
#       - run: |
#           echo "Files after checkout : "
#           ls

#       - run: |
#           echo "Node version before setup : "
#           node -v

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 24
      
#       - run: |
#           echo "Node version after setup : "
#           node -v
#           npm -v

### Sequential jobs

# jobs:
#   first:
#     runs-on:
#       ubuntu-latest
#     steps:
#       - name: first jobs
#         run: echo "This is first job"
  
#   second:
#     # waits for the first job to complete
#     # if first job fails the second job never starts
#     needs: first 
#     runs-on:
#       ubuntu-latest
#     steps:
#       - name: second job
#         run: echo "This is second job"


### Env, secrets and contexts

# name: CI CD | second lesson
# on:
#   push:
#     branches:
#       - main

# env:
#   APP_NAME: DEMO APP
#   APP_SECRET: ${{ secrets.APP_SECRET_VALUE}}

# jobs:
#   first:
#     runs-on: ubuntu-latest
#     steps:
#       - name: First step
#         run: echo "Env variable $APP_NAME"
#       - name: second step
#         run: echo "Secret $APP_SECRET"
#   second:
#     runs-on: ubuntu-latest
#     steps:
#       - name: expressions
#         run: |
#           echo ${{ github.actor }}
#           echo ${{ github.repository }}
#           echo ${{ github.ref_name }}
#           echo ${{ runner.os }}


### If statement with functions

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Running CI"
#       - if: github.ref == 'refs/heads/main'
#         run: echo "Deploying..."
#       - if: always()
#         run: echo "Finished"


### Practice test

# name: CI/CD
# on:
#   push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Building..."
  
#   test:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Testing..."
  
#   deploy:
#     needs: test
#     if: success() && github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "deploying..."


### Inputs and Outputs

# name: CI/CD | Inputs & Outputs
# on:
#   workflow_dispatch:
#     inputs:
#       env:
#         type: choice
#         options:
#           - dev
#           - staging
#           - prod
#       runTests:
#         type: boolean
# jobs:
#   first:
#     runs-on: ubuntu-latest
#     outputs:
#       version: ${{ steps.node.outputs.version }}
#     steps:
#       - id: node
#         run: |
#           echo "env: ${{ inputs.env }}"
#           echo "runTests: ${{ inputs.runTests }}"
#           echo "version=v1.2.0" >> $GITHUB_OUTPUT
#       - run: echo "${{ steps.node.outputs.version }}"
#   second:
#     needs: first
#     if: ${{ inputs.runTests }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "version ${{ needs.first.outputs.version }}"


### Atrifacts

# name: CI/CD | Artifacts
# on:
#   push
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/upload-artifact@v4
#         with:
#           name: test-reports
#           path: reports/
#           retention-days: 2

#   verify:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/download-artifact@v4
#         with:
#           name: test-reports
#           path: downloaded-reports
#       - run: |
#           ls -R
#           cat downloaded-reports/test.txt
#           cat downloaded-reports/result.txt


### cache

name: CI/CD | cache
on:
  push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - id: cache-id
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: echo "cache hit - ${{ steps.cache-id.outputs.cache-hit }}"
      - run: |
          npm install
          npm test
      
      