# name: CI CD | second lesson

# on:
#   push:
#     branches:
#       - main

# env:
#   APP_NAME: DEMO APP
#   APP_SECRET: ${{ secrets.APP_SECRET_VALUE}}

# jobs:
#   first:
#     runs-on: ubuntu-latest
#     steps:
#       - name: First step
#         run: echo "Env variable $APP_NAME"
#       - name: second step
#         run: echo "Secret $APP_SECRET"
#   second:
#     runs-on: ubuntu-latest
#     steps:
#       - name: expressions
#         run: |
#           echo ${{ github.actor }}
#           echo ${{ github.repository }}
#           echo ${{ github.ref_name }}
#           echo ${{ runner.os }}

name: CI/CD

on:
  push

jobs:
  runs-on: ubuntu-latest

  steps:
    - run: echo "Running CI"

    - if: github.ref == 'refs/heads/main'
      run: echo "Deploying..."